### ISSUE TITLE
Need help here

### ISSUE THREAD

**Issue by DaCooladeMan** [lonefelidae16/extra-sounds#7]
Hey! So, I when I tried to build this mod with the 'gradlew build' command, it failed every single time. But when I built it with 'gradlew.bat' it worked. Is that what I was supposed to do? or... anyways, my main problem here, is that in the build section of the file, there are a bunch of .jar files. Am I supposed to just copy all of them and paste them into my mod folder or am I supposed to compress it all into 1 file then do it? If you can help me with this, please do.

Edit: So, I just copied all 85 files and pasted it into my mod folder. When I ran the game, the fabric loader gave me many errors:

Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod fabric-biome-api-v1
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:478)
	... 3 more

I don't know if it's an incompatibility error or what, but I really need help.

**Comment by lonefelidae16** [comment]
Please follow [this guide](https://github.com/lonefelidae16/extra-sounds/wiki/How-to-build-this-project). The required mod file will be generated at `build/libs/extrasounds-[version]+[MCversion].jar`. Single file.

85 files...? Referring to the error message you mentioned, I think they are in the loom-cache, and perhaps they named with `net_fabricmc_yarn_[MCversion]_build_[yarnVersion]_v2.[namespace]-[modName]-[modVersion].jar`. The remapped Jars shouldn’t place to the mods folder; they conflict with the Fabric API. and crash with such a message.

> I when I tried to build this mod with the 'gradlew build' command, it failed every single time.

I assume you were trying to build with Windows PowerShell? If so, the command will be `.\gradlew.bat build`. on the other hand with Command Prompt, `gradlew build` works.

**Comment by DaCooladeMan** [comment]
> Please follow [this guide](https://github.com/lonefelidae16/extra-sounds/wiki/How-to-build-this-project). The required mod file will be generated at `build/libs/extrasounds-[version]+[MCversion].jar`. Single file.
> 
> 85 files...? Referring to the error message you mentioned, I think they are in the loom-cache, and perhaps they named with `net_fabricmc_yarn_[MCversion]_build_[yarnVersion]_v2.[namespace]-[modName]-[modVersion].jar`. The remapped Jars shouldn’t place to the mods folder; they conflict with the Fabric API. and crash with such a message.
> 
> > I when I tried to build this mod with the 'gradlew build' command, it failed every single time.
> 
> I assume you were trying to build with Windows PowerShell? If so, the command will be `.\gradlew.bat build`. on the other hand with Command Prompt, `gradlew build` works.

No, no no. I was trying to build with cmd. I watched a tutorial on how to get the trainguy's animation overhaul mod, because I thought the process was similar to this, and while it is, the gradley build command, mentioned in the tutorial didn't work for me, but then I saw the gradlew.bat file in .zip file so I built with gradlew.bat and it worked. Anyways, thanks. I'll try this out.
